config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources:articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :description, presence: true
    validates :description, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles=Article.all
  end
  
  def new
    @articles=Article.new  
     
  end
    
    
  def create
    @articles=Article.new(article_params)
    if @articles.save
      redirect_to articles_path, notice: "created"
    else
      render 'new'
    end
  end
    
  def edit
    @articles=Article.find(params[:id])
        
        
  end
    
  def show
    @articles=Article.find(params[:id])   
        
  end
    
  def destroy
    @articles=Article.find(params[:id])
    @articles.destroy
    redirect_to articles_path, notice:"article delete"  
        
  end
    
  def update
    @articles = Article.find(params[:id])
    if @articles.update(article_params)
       redirect_to articles_path, notice:"Article was updated"
    else
       render 'edit'
    end
    
  end
    
    
  private
  
    def article_params
    params.require(:article).permit(:title,:description)
  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_with(model: @articles,local: true, url: article_path) do |form| %>
<% if @articles.errors.any? %>
    <div id="error_explanation">
      <h2><%= @articles.errors.count %>errors occurred.</h2>
      <ul>

      <% @articles.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="article_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div><br>
  <div class="article_title">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <br>
  <%= form.submit %>
<% end %>

app/views/articles/index.html.erb
<h1>Welcome to Articles</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Descriptiont</th></th>
  </tr>
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td><nbspc></nbspc>
    <td><%= article.description %></td>
     <td><%= link_to 'Check the details', article_path(article.id) %></td>
     <td><%= link_to "Edit article", edit_article_path(article.id),data: {confirm: "Are you sure?"} %></td>
     <td><%=link_to 'delete', article_path(article.id),method: :delete,data:{confirm:"Are you sure delete?"}%></td>    
     </tr>
     <%end%>
     </table>
     <br>
     <%=link_to'create new article',new_article_path%>

app/views/articles/new.html.erb
<%= form_with(model: Article.new,local: true, url: articles_path) do |form| %>
<% if @articles.errors.any? %>
    <div id="error_explanation">
      <h2><%= @articles.errors.count %>errors occurred.</h2>
      <ul>

      <% @articles.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="article_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div><br>
  <div class="article_title">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <br>
  <%= form.submit %>
<% end %>

app/views/articles/show.html.erb
<h1> Hello new readers</h1>
<p>TITLE:<%=@articles.title%></p>
<p>DESCRIPTION:<%=@articles.description%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAssignment2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>